### ISSUE TITLE
MonetaryAmountFormat for Locale.ROOT expects non breaking space separator between currency and amount on JDK > 8

### ISSUE THREAD

**Issue by olivergierke** [JavaMoney/jsr354-ri#208]
The `MonetaryAmountFormat` produced for a `Locale.ROOT` produces non-breaking spaces between currency and amount value on JDKs > 8. On the parsing side of things, this causes that source strings using a normal space (character value of 32) to not be detected properly and the parsing to fail.

```java
MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(Locale.ROOT);

MonetaryAmount source = Money.of(123456.78, "EUR");
String formatted = format.format(source);

System.out.println(formatted); // "EUR 123,456.78", space is a 32 on JDK 8, a 160 on JDK 9 and 10
System.out.println((int) formatted.toCharArray()[3]); // JDK 8: 32, JDK 9: 160, JDK 10: 160

MonetaryAmount result = format.parse("EUR 123,456.78"); // Space is char of 32 (standard space)
```

On JDK 9 and 10 the last line throws the following exception:

```
javax.money.MonetaryException: Error parsing CurrencyUnit.
	at org.javamoney.moneta.internal.format.CurrencyToken.parse(CurrencyToken.java:227)
	at org.javamoney.moneta.internal.format.DefaultMonetaryAmountFormat.parse(DefaultMonetaryAmountFormat.java:190)
	at org.salespointframework.MonetaryAmountAttributeConverterTest.deserializesFormattedValues(MonetaryAmountAttributeConverterTest.java:81)
	at …
Caused by: UnknownCurrencyException [currencyCode=]
	at javax.money.spi.MonetaryCurrenciesSingletonSpi.getCurrency(MonetaryCurrenciesSingletonSpi.java:74)
	at javax.money.Monetary.getCurrency(Monetary.java:384)
	at org.javamoney.moneta.internal.format.CurrencyToken.parse(CurrencyToken.java:195)
	... 25 more
```

**Comment by olivergierke** [comment]
What's interesting to note is that the actual exception occurring first is coming from `java.text.DecimalFormat.parse(…)`. The `ParseException` is translated into an error on the `ParseContext` (in `AmountNumberToken.parseToken(…)`) which is translated into `MonetaryParseException`. I guess it's already unfortunate that the original exception gets lost in that step.

What's even more unfortunate then, is that `DefaultMonetaryAmountFormat.parse(…)` catches that exception and falls back to try the negative tokens, which then tries to parse the currency again, and fails on that. That in turn causes the exception I eventually see.

I.e. a couple of more general questions:

- should `DefaultMonetaryAmountFormat.parse(…)`'s handling of negative tokens use a fresh `ParserContext` at the expense of trying to resolve the currency twice?
- should `AmountNumberToken.parseToken(…)`/`….parse(…)` properly propagate the original exception? Looks like `MonetaryParseException` currently doesn't expose any constructor that takes a source exception at all.

**Comment by keilw** [comment]
@olivergierke It is not yet official, but because Credit Suisse has been inactive for too long, the former (right now under the current JCP a JSR that's Final has no EG any more) EG members and active participants of JavaMoney start to think about a new version. @atsticks is likely to lead it on behalf of Trivadis. Would you/Pivotal be happy to either join the EG or at least be listed as "Supporting this JSR"?

**Comment by olivergierke** [comment]
This is becoming a real showstopper for a post-Java-8 migration. Any chance you guys start looking into this?

**Comment by keilw** [comment]
I'm afraid until Credit Suisse decides to either take the lead or allow us with the help of the PMO/EC to start `3.2.2.5 Relinquishing ownership` (https://jcp.org/en/procedures/jcp2#3.2.2) there is not much we can do, the Expert Group officially no longer exists, we got to get this moving not only for a post-Java 8 or 9 time.

**Comment by olivergierke** [comment]
Erm, can you elaborate why this issue was closed? Are you not planning to fix this, i.e. stay Java 8 compatible only?

I can't quite follow why this is becoming an EG discussion. I filed a ticket against a bug in an open source library. Whether this library implements a spec doesn't actually matter, does it? Or does this mean that Moneta is not actually maintained at all anymore? If so, that probably that deserves a significantly broader announcement.

**Comment by keilw** [comment]
It sounded like this is a duplicate of #210 If someone (a JCP member) wishes to create a PR, please do so. We just merged a few others, but without a Maintenance Lead who should take care of that, there won't be a new release every few weeks or months. Especially because for JSR 354 we're obliged to provide all relevant fixes (something that happens only beyond Java 10 may not be something we need to fix there) also for the backports. So of the 17 open issues at least 15 or so are likely relevant to both moneta and moneta-bp, hence it'll take time before a new release.

**Comment by keilw** [comment]
Besides most Apache and all Eclipse projects are not allowed to use either this project or the BP unless https://github.com/JavaMoney/jsr354-api/issues/56 and related issues are resolved. And that is nothing a spontaneous bugfix release every now and then can fix.

**Comment by odrotbohm** [comment]
Verified fixed with 1.4 snapshots (as indicated in #210).

**Comment by odrotbohm** [comment]
The 1.4 snapshots stopped working for me on JDK 11. The release of 20190913.141310-138 has the print and parsing symmetry completely broken as it prints currency codes as postfix but seems to expect them as prefix on parsing. Has there anything changed in the locale detection?

A build I can successfully run my tests on is 20190227.142924-101.

**Comment by keilw** [comment]
So it works on JDK 8 or everything below 11? @atsticks any idea what could be the reason? Won't reopen it as of now, but we have to see how to handle it. The MR1 is not too likely before the JCP EC got reelected and able to vote on such things.

**Comment by odrotbohm** [comment]
```java
Money money = Money.of(1.2, "EUR");

assertThat(money).isEqualTo(Money.parse(money.toString()));
```

This succeeds for 1.3 but fails for current 1.4 snapshots, both on Java 8 and 11.

> The MR1 is not too likely before the JCP EC got reelected and able to vote on such things.

I still don't get why an open source implementation of a spec cannot issue a bugfix release on its own. There's no need for a spec update whatsoever. I'd even be fine with a 1.3.1 if it's about the version numbers.

**Comment by keilw** [comment]
MR1 is about the spec, all the license changes that some communities like Spring may care less, but others like Eclipse won't accept the spec and API until it is addressed.
I tried to reproduce the top most snipped but it shows no change between Java 8 and 12 with the 1.4-SNAPSHOT. 

The assertion above may fail because the demos I used show,` money.toString()` prints "EUR123,456.78", but format.format(money) formats  "EUR 123,456.78" which also can be parsed again, see https://github.com/JavaMoney/javamoney-examples/blob/master/console/javamoney-console-java10/src/main/java/org/javamoney/examples/console/java10/FormattingLocaleDemo.java.
I ran it in Java 8 to 12 and it never shows "160" in the line you highlighted, so it seems the JDK fixed it or a fix in Moneta did, but it works in the current snapshot. This ticket was about `MonetaryAmountFormat`, the fact that `Money.toString()` may use it differently, please raise another issue for that.

**Comment by odrotbohm** [comment]
I've created #319 to keep track of the asymmetry issue. I don't that one in particular has anything to do with the JDK version. It'll just keep us from upgrading to 1.4, which – in the absence of 1.3.1 release – we apparently need to to make Moneta work in JDK 11.
